# Generated by Django 5.0.2 on 2024-05-22 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gannt_start_column', models.IntegerField(default='9')),
                ('week_number_row', models.IntegerField(default='4')),
                ('start_row', models.IntegerField(default='5')),
                ('start_column', models.IntegerField(default='2')),
                ('end_column', models.IntegerField(default='6')),
                ('pic_column', models.IntegerField(default='8')),
                ('email_column', models.IntegerField(default='61')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
