# Generated by Django 5.0.2 on 2024-05-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_task_due_date_alter_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='New', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='New', max_length=30),
        ),
    ]
