# Generated by Django 5.0.2 on 2024-05-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_project_status_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='Open', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='Closed', max_length=30),
        ),
    ]
