# Generated by Django 5.0.2 on 2024-05-23 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_project_status_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jenis', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='priority',
            name='jenis',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.status'),
        ),
    ]
