# Generated by Django 5.0.2 on 2024-05-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
