# Generated by Django 5.0.2 on 2024-06-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_task_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
