# Generated by Django 5.0.2 on 2024-06-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_feedback_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
